# Generated by Django 5.2.5 on 2026-03-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_usagehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemuser',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
